name: Add a portfolio
description: Request a portfolio be added to our evergrowing database!
title: 'Portfolios » '
labels: ['addition']
body:
  - type: markdown
    attributes:
      value: |
        Please make sure to include all the required fields to get your portfolio added.
  - type: input
    id: download-portfolio
    attributes:
      label: 'Download for your portfolio'
      description: Please provide a direct download link through dropbox or google drive.
      placeholder: Your drive link
    validations:
      required: true
  - type: dropdown
    id: award-type
    attributes:
      label: 'Award Type'
      description: Provide the award your team recieved the year of this portfolio
      options:
        - Inspire
        - Control
        - Motivate
        - Innovate
        - Connect
        - Design
        - Think
    validations:
      required: true
  - type: dropdown
    id: award-ranking
    attributes:
      label: 'Award Ranking'
      description: What ranking did your team get with this award?
      options:
        - 1
        - 2
        - 3
    validations:
      required: true
  - type: dropdown
    id: field
    attributes:
      label: 'Field of award'
      description: Where did you get this award?
      options:
        - Worlds
        - Regional
        - Qualifier
    validations:
      required: true
  - type: input
    id: team-name
    attributes:
      label: 'Team Name'
      description: What is your team's name?
      placeholder: Hivemind
    validations:
      required: true
  - type: input
    id: team-number
    attributes:
      label: 'Team Number'
      description: What is your team's number?
      placeholder: '23396'
    validations:
      required: true
  - type: input
    id: team-region
    attributes:
      label: 'Team Region'
      description: What is your team's Region?
      placeholder: Tennessee
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: 'Code of Conduct'
      description: |
        By submitting this issue, you agree that we are allowed to distribute this information provided through this issue. Additionally, you agree that
        this information can be publised to our database of portfolios, and that you own or have permission to use the assets you are submitting.
      options:
        - label: I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.
          required: true
