export default function PrivacyPolicy() {
	return (
		<>
			<div className="container mx-auto py-8 md:py-12 lg:py-24 max-w-4xl">
				<div className="space-y-3">
					<h1 className="text-2xl font-bold">Privacy Policy</h1>
					<em>
						<p className="opacity-70">Last updated: 12/29/2023</p>
					</em>
				</div>
				<div className="my-12 space-y-4">
					<h2 className="text-xl font-semibold">Introduction</h2>
					<p className="opacity-70">
						Welcome to <strong>Portfolios</strong>, this instance is operated by the non-profit
						organization <strong>Hivemind Robotics</strong>, which is registered under Hackclub
						Bank.
					</p>
					<p className="opacity-70">
						Hivemind Robotics (&ldquo;us&ldquo;, &ldquo;we&ldquo;, or &ldquo;our&ldquo;) operates
						this instance of Portfolios located at{' '}
						<a
							href="https://portfolios.hivemindrobotics.net/"
							className="underline hover:opacity-70 transition-all"
						>
							portfolios.hivemindrobotics.net
						</a>{' '}
						(hereinafter reffered to as &ldquo;<strong>Service</strong>&ldquo;)
					</p>
					<p className="opacity-70">
						Our Privacy Policy governs you to visit{' '}
						<a
							href="https://portfolios.hivemindrobotics.net/"
							className="underline hover:opacity-70 transition-all"
						>
							portfolios.hivemindrobotics.net
						</a>
						{', '}
						and explains how we collect, safeguard, and diclose information that results from your
						use of our Service.
					</p>
					<p className="opacity-70">
						We use your data to provide and improve Service. By using Service, you agree to the
						collection and use of information in accordance to this policy. Unless otherwise defined
						in this Privacy Policy, the terms of use and Privacy Policy have the same meanings as
						our Terms & Conditions.
					</p>
					<p className="opacity-70">
						Our Terms & Conditions (&ldquo;<strong>Terms</strong>&ldquo;) govern all use of our
						service together with the Privacy Policy which constitutes your agreement with us
						(&ldquo;<strong>agreement</strong>&ldquo;)
					</p>
					<h3 className="text-xl font-semibold py-4">Definitions</h3>
					<p className="opacity-70">
						<strong>SERVICE</strong> means{' '}
						<a
							href="https://portfolios.hivemindrobotics.net/"
							className="underline hover:opacity-70 transition-all"
						>
							portfolios.hivemindrobotics.net
						</a>{' '}
						operated by Hivemind Robotics
					</p>
					<p className="opacity-70">
						<strong>PERSONAL DATA</strong> means data about a living individual who can be
						identified from that data (or from those and other information either in our posession
						or likely to come in our posession).
					</p>
					<p className="opacity-70">
						<strong>USAGE DATA</strong> is data automatically either generated by the use of Service
						or from Service infrastructure itself (for example, the duration of a page visit)
					</p>
					<p className="opacity-70">
						<strong>COOKIES</strong> are small files stored on your device (computer or mobile
						device).
					</p>
					<p className="opacity-70">
						<strong>DATA CONTROLLER</strong> means a natrual or legal person who (either alone or
						jointly or in common with other persons) determines the purposes for which and the
						manner in which personal data are, or are to be, processed. For the purpose of this
						Privacy Policy, we are a Data Controller of your data.
					</p>
					<p className="opacity-70">
						<strong>DATA PROCESSORS (OR SERVICE PROVIDERS)</strong> means a natrual or legal person
						who processes the data on behalf of the Data Controller. We may use Service Providers in
						order to process your data more effectively.
					</p>
					<p className="opacity-70">
						<strong>DATA SUBJECT</strong> is any living individual who is the subject of Personal
						Data.
					</p>
					<p className="opacity-70">
						<strong>USER</strong> is the individual using our Service. The User corresponds to the
						Data Subject, who is the subject of Personal Data.
					</p>
					<h2 className="text-xl font-bold py-4">Information Collection and Use</h2>
					<p className="opacity-70">
						We collect several different types of information for various purposes to provide and
						improve our Service to you.
					</p>
					<h2 className="text-xl font-bold py-4">Types of Data Collected</h2>
					<h3 className="text-md font-bold pb-4">Personal Data</h3>
					<p className="opacity-70">
						While using our Service, we may ask you to provide us with certain personally
						identifiable information that can be used to identify you (&ldquo;
						<strong>Personal Data</strong>&ldquo;). Personally identifiable information may include,
						but is not limited to:
						<ul className="list-disc ms-4 my-5 space-y-3">
							<li>Email Address</li>
							<li>Your Name</li>
							<li>Your FIRST Team Number and Team Name</li>
						</ul>
						We may use your Personal Data to contact you regarding your account, marketing, or
						promotional materials. You are free to opt-out of recieving any, or all, of these
						communications from us by following the unsubscribe link.
					</p>
					<h3 className="text-md font-bold py-4">Usage Data</h3>
					<p className="opacity-70">
						We may also collect information that your browser sends whenever you visit our Service
						or when you access our Service through your mobile device.
					</p>
					<p className="opacity-70">
						This Usage Data may include information such as your computer&apos;s Internet Protocol
						address (e.g. IP address), browser type, browser version, the pages of our Service that
						you visit, the time of date that you visit, the time spent on those pages, unique device
						identifiers, and other diagnostic data.
					</p>
					<p className="opacity-70">
						When you access our Service through your mobile device, this Usage Data may include
						information such as the type of mobile device you use, your mobile device unique ID, the
						IP address of your mobile device, your mobile operating system, the type of mobile
						internet that you use, unique identifiers and other diagnostic data.
					</p>
					<h3 className="text-md font-bold py-4">Tracking Cookies Data</h3>
					<p className="opacity-70">
						We use cookies and similar tracking technologies to track the activity on our Service
						and we hold certain information.
					</p>
					<p className="opacity-70">
						Cookies are files with a small amount of data which may include an anonymous unique
						identifier. Cookies are sent to your browser and are stored on your device. Other
						tracking technologies are also used as tags and scripts to collect and track information
						and to improve and analyze our Service.
					</p>
					<p className="opacity-70">
						Examples of cookies we use:
						<ul className="list-disc ms-4 my-5 space-y-3">
							<li>
								<strong>Session Cookies</strong>: We use Session Cookies to operate our Service
							</li>
							<li>
								<strong>Preference Cookies</strong>: We use Preference Cookies to remember your
								preferences and various settings (e.g. Dark or Light theme).
							</li>
							<li>
								<strong>Security Cookies</strong>: We use Security Cookies to manage your
								account&apos;s security.
							</li>
						</ul>
					</p>
					<h2 className="text-xl font-bold py-4">Use of Data</h2>
					<p className="opacity-70">
						Hivemind Robotics uses the collected data for various purposes
						<ul className="list-disc ms-4 my-5 space-y-3">
							<li>to provide and maintain our Service;</li>
							<li>to notify you about changes to our Service;</li>
							<li>to provide user support;</li>
							<li>
								to gather analysis or valuable information so that we can improve our Service;
							</li>
							<li>to monitor the usage of our Service;</li>
							<li>to detect, prevent, or address technical issues;</li>
							<li>to fufill any other purpose which you provide it;</li>
							<li>
								to provide you with notices about your account and/or portfolios you own, including
								termination, report analysis, email-instructions, etc.;
							</li>
							<li>
								to provide you with news, special offers, and general information about other goods,
								services, and events which we offer unless you have opted not to receive such
								information
							</li>
							<li>in any other way we may describe when you provide the information;</li>
							<li>for any other purpose with your consent;</li>
						</ul>
					</p>
					<h2 className="text-xl font-bold py-4">Retention of Data</h2>
					<p className="opacity-70">
						We will retain your Personal Data only for as long as is necessary for the purposes set
						out in this Privacy Policy. We will retain and use your Personal Data to the extent
						necessary to provide with legal obligations, and resolve disputes.
					</p>
					<p className="opacity-70">
						We will also retain Usage Data for internal analysis purposes. Usage Data is generally
						obtained for a shorter period, except when this data is used to strengthen security or
						improve the functionality of our Service, or we are legally obligated to retain this
						data for a longer period of time.
					</p>
					<h2 className="text-xl font-bold py-4">Transfer of Data</h2>
					<p className="opacity-70">
						Your information, including Personal Data, may be transferred to, and maintained on,
						computers outside of your state, province, country, or other governmental jurisdiction
						where data protection laws may differ from those of your jurisdiction.
					</p>
					<p className="opacity-70">
						If you are located outside of the United States and choose to provide information to us,
						please note that we transfer the data, including your Personal Data, to the United
						States and process it there.
					</p>
					<p className="opacity-70">
						Your consent to this Privacy Policy followed by your submission of such information
						represents your agreement to this transfer.
					</p>
					<p className="opacity-70">
						Hivemind Robotics will take all steps reasonably necessary to ensure that your data is
						treated securely and in accordance to this Privacy Policy and no transfer of your
						Personal Data will take place to an organization or a country unless there are adequate
						controls in place including the security of your data and personal information.
					</p>
					<h2 className="text-xl font-bold py-4">Disclosure of Data</h2>
					<p className="opacity-70">
						We may disclose personal information that we collect or you provide:
					</p>
					<h3 className="text-md font-bold pb-2">Disclosure to Law Enforcement</h3>
					<p className="opacity-70">
						Under certain circumstances, we may need to disclose your personal information if we are
						required to do so by law or in response to valid requests by public athorities.
					</p>
					<h3 className="text-md font-bold pb-2">
						Other cases. We may disclose your information also:
					</h3>
					<p className="opacity-70">
						<ul className="list-disc ms-4 my-5 space-y-3">
							<li>to our subsidiaries or affiliates;</li>
							<li>to service providers, and other third parties we use to support our Service;</li>
							<li>to fulfill the purpose for which you provide it;</li>
							<li>for any other purpose disclosed by us when you provide the information;</li>
							<li>with your consent in any other cases;</li>
						</ul>
					</p>
					<h2 className="text-xl font-bold py-4">Security of Data</h2>
					<p className="opacity-70">
						The security of your data is important to us but remember that no method of transmission
						over the Internet or method of electronic storage is <b>100% secure</b>. While we strive
						to use commercially acceptable means to protect your Personal Data, we cannot guarantee
						its absolute security.
					</p>
					<h2 className="text-xl font-bold py-4">CI/CD Tooling</h2>
					<p className="opacity-70">
						We may use third-party service providers to automate the deployment of our service.
					</p>
					<h3 className="text-md font-bold pb-2">GitHub</h3>
					<p className="opacity-70">GitHub is provided by GitHub Inc.</p>
					<p className="opacity-70">
						GitHub is a development platform to host and review code, manage projects, and build
						software.
					</p>
					<p className="opacity-70">
						For more information on what data GitHub collects for what purpose and how the
						protection of the data is ensured, please visit GitHub Privacy Policy page{' '}
						<a
							href="https://docs.github.com/en/site-policy/privacy-policies/github-privacy-statement"
							className="underline hover:opacity-70 transition-all"
						>
							here
						</a>
						.
					</p>
					<h2 className="text-xl font-bold py-4">Web and Database Hosting</h2>
					<p className="opacity-70">
						We may use third-party service providers to host our websites, and deploy our databases.
					</p>
					<h3 className="text-md font-bold pb-2">Vercel</h3>
					<p className="opacity-70">Vercel is provided by Vercel Inc.</p>
					<p className="opacity-70">
						Vercel is a development platform which provides easy-to-use web and database deployment
						solutions.
					</p>
					<p className="opacity-70">
						For more information on what data Vercel collects for what purpose and how the
						protection of your data is ensured, please visit the Vercel Privacy Policy page{' '}
						<a
							href="https://vercel.com/legal/privacy-policy"
							className="underline hover:opacity-70 transition-all"
						>
							here
						</a>
						.
					</p>
					<h2 className="text-xl font-bold py-4">Analytics</h2>
					<p className="opacity-70">
						We may use user analytics to analyse user experience, UI/UX, and track the activity of
						our services so we can scale them if we need to.
					</p>
					<h3 className="text-md font-bold pb-2">PostHog</h3>
					<p className="opacity-70">PostHog is provided by PostHog Inc.</p>
					<p className="opacity-70">
						PostHog is a analytics platform that allows us to view your experience on Portfolios.
					</p>
					<p className="opacity-70">
						For more information on what data PostHog collects for what purpose and how the
						protection of your data is ensured, please visit the PostHog Privacy Policy page{' '}
						<a
							href="https://posthog.com/privacy"
							className="underline hover:opacity-70 transition-all"
						>
							here
						</a>
						.
					</p>
					<h2 className="text-xl font-bold py-4">Children&apos;s Privacy</h2>
					<p className="opacity-70">
						Our Services are not intended to be used by logged in users who are under the age of 13
						(&ldquo;<strong>Children</strong>&ldquo;)
					</p>
					<p className="opacity-70">
						We do not knowingly collect personally identifiable information from Children under 13.
						If you become aware that a Child has provided us with Personal Data, please contact us.
						If we become aware that we have collected Personal Data from Children without
						verification of parental consent, we will take steps to remove this data from our
						servers.
					</p>
					<h2 className="text-xl font-bold py-4">Changes to This Privacy Policy</h2>
					<p className="opacity-70">
						We may update this Privacy Policy from time to time. We will notify you of any changes
						by posting the new Privacy Policy on this page.
					</p>
					<p className="opacity-70">
						We will let you know via email and/or a notice on your user dashboard, prior to the
						changes becoming effective and update the &ldquo;Last Updated&ldquo; date at the top of
						this Privacy Policy.
					</p>
					<p className="opacity-70">
						You are advised to review this Privacy Policy periodically for any changes. Changes to
						this Privacy Policy are effective when they are posted on this page.
					</p>
					<h2 className="text-xl font-bold py-4">Contact Us</h2>
					<p className="opacity-70">
						If you have any questions or concerns about this privacy policy, please contact us by
						email at{' '}
						<a
							href="mailto:webm@hivemindrobotics.net"
							className="underline hover:opacity-70 transition-all"
						>
							webm@hivemindrobotics.net
						</a>{' '}
						or by using the contact form on our{' '}
						<a
							target="_blank"
							href="https://hivemindrobotics.net/team#contact"
							className="underline hover:opacity-70 transition-all"
						>
							main site
						</a>
					</p>
				</div>
			</div>
		</>
	);
}
